server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1.0
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    #    web: debug
    com.tdubuis: debug

spring:
#  main:
#    banner-mode: off
  sql:
    init:
      mode: always #For generate fakeData with data.sql file
  application:
    name: MovieApp
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/movieapp}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}
  jpa:
    open-in-view: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    #      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#    show-sql: ${SHOW_SQL:true}
  hateoas:
    use-hal-as-default-json-media-type: false
